// Offline fallback for the RCx_OPTION aux-function enum (RC_Channel::AUX_FUNC), keyed by vehicle
// family like COPTER_MODE_NAMES/PLANE_MODE_NAMES in constants.ts. RcSetupSection.tsx normally
// fetches this list live from ArduPilot's own parameter docs (fetchParamDocs), which is the more
// current source and always wins once it loads - but that fetch needs internet access, and a
// real vehicle is often being configured in the field with none. Without this fallback, every
// previously-set RCx_OPTION shows as a bare numeric code ("#77") until (if ever) the docs fetch
// succeeds, even for common, stable functions ArduPilot has shipped for years.
//
// Snapshotted from https://autotest.ardupilot.org/Parameters/{ArduCopter,ArduPlane}/apm.pdef.xml
// on 2026-08-20 (the same source fetchParamDocs uses live). The two vehicle families genuinely
// differ - e.g. code 77 is "TAKEOFF Mode" for Plane but doesn't exist at all for Copter, and code
// 51 is "MANUAL Mode" for Plane but "User Function 1" for Copter - so, like the mode-name tables,
// this must stay two separate per-vehicle maps rather than one merged one. Only these two vehicle
// families have a fallback here, matching COPTER_MODE_NAMES/PLANE_MODE_NAMES's own scope - Rover/
// Sub/Tracker still require a live docs fetch, same as their flight-mode names already do.
export const AUX_FUNCTION_NAMES_COPTER: Readonly<Record<number, string>> = {
  0: "Do Nothing",
  2: "FLIP Mode",
  3: "Simple Mode",
  4: "RTL",
  5: "Save Trim",
  7: "Save WP",
  9: "Camera Trigger",
  10: "RangeFinder Enable",
  11: "Fence Enable",
  13: "Super Simple Mode",
  14: "Acro Trainer",
  15: "Sprayer Enable",
  16: "AUTO Mode",
  17: "AUTOTUNE Mode",
  18: "LAND Mode",
  19: "Gripper",
  21: "Parachute Enable",
  22: "Parachute Release",
  23: "Parachute 3pos",
  24: "Auto Mission Reset",
  25: "AttCon Feed Forward",
  26: "AttCon Accel Limits",
  27: "Retract Mount1",
  28: "Relay1 On/Off",
  29: "Landing Gear",
  30: "Lost Copter Sound",
  31: "Motor Emergency Stop",
  32: "Motor Interlock",
  33: "BRAKE Mode",
  34: "Relay2 On/Off",
  35: "Relay3 On/Off",
  36: "Relay4 On/Off",
  37: "THROW Mode",
  38: "ADSB Avoidance Enable",
  39: "PrecLoiter Enable",
  40: "Proximity Avoidance Enable",
  41: "ArmDisarm (4.1 and lower)",
  42: "SMARTRTL Mode",
  43: "InvertedFlight Enable",
  44: "Winch Enable",
  45: "Winch Control",
  46: "RC Override Enable",
  47: "User Function 1",
  48: "User Function 2",
  49: "User Function 3",
  52: "ACRO Mode",
  55: "GUIDED Mode",
  56: "LOITER Mode",
  57: "FOLLOW Mode",
  58: "Clear Waypoints",
  60: "ZigZag Mode",
  61: "ZigZag SaveWP",
  62: "Compass Learn",
  65: "GPS Disable",
  66: "Relay5 On/Off",
  67: "Relay6 On/Off",
  68: "STABILIZE Mode",
  69: "POSHOLD Mode",
  70: "ALTHOLD Mode",
  71: "FLOWHOLD Mode",
  72: "CIRCLE Mode",
  73: "DRIFT Mode",
  75: "SurfaceTrackingUpDown",
  76: "STANDBY Mode",
  78: "RunCam Control",
  79: "RunCam OSD Control",
  80: "VisOdom Align",
  81: "Disarm",
  83: "ZigZag Auto",
  84: "AirMode",
  85: "Generator",
  90: "EKF Source Set",
  94: "VTX Power",
  99: "AUTO RTL",
  100: "KillIMU1",
  101: "KillIMU2",
  102: "Camera Mode Toggle",
  103: "EKF lane switch attempt",
  104: "EKF yaw reset",
  105: "GPS Disable Yaw",
  109: "use Custom Controller",
  110: "KillIMU3",
  111: "Loweheiser starter",
  112: "SwitchExternalAHRS",
  113: "Retract Mount2",
  151: "TURTLE Mode",
  152: "SIMPLE heading reset",
  153: "ArmDisarm (4.2 and higher)",
  154: "ArmDisarm with AirMode  (4.2 and higher)",
  158: "Optflow Calibration",
  159: "Force IS_Flying",
  161: "Turbine Start(heli)",
  162: "FFT Tune",
  163: "Mount Yaw Lock",
  164: "Pause Stream Logging",
  165: "Arm/Emergency Motor Stop",
  166: "Camera Record Video",
  167: "Camera Zoom",
  168: "Camera Manual Focus",
  169: "Camera Auto Focus",
  171: "Calibrate Compasses",
  172: "Battery MPPT Enable",
  174: "Camera Image Tracking",
  175: "Camera Lens",
  177: "Mount LRF enable",
  178: "FlightMode Pause/Resume",
  180: "Test autotuned gains after tune is complete",
  182: "AHRS AutoTrim",
  185: "Mount Roll/Pitch Lock",
  186: "Mount POI Lock",
  187: "EKF Reset",
  212: "Mount1 Roll",
  213: "Mount1 Pitch",
  214: "Mount1 Yaw",
  215: "Mount2 Roll",
  216: "Mount2 Pitch",
  217: "Mount2 Yaw",
  218: "Loweheiser throttle",
  219: "Transmitter Tuning",
  300: "Scripting1",
  301: "Scripting2",
  302: "Scripting3",
  303: "Scripting4",
  304: "Scripting5",
  305: "Scripting6",
  306: "Scripting7",
  307: "Scripting8",
  308: "Scripting9",
  309: "Scripting10",
  310: "Scripting11",
  311: "Scripting12",
  312: "Scripting13",
  313: "Scripting14",
  314: "Scripting15",
  315: "Scripting16",
  316: "Stop-Restart Scripting",
};

export const AUX_FUNCTION_NAMES_PLANE: Readonly<Record<number, string>> = {
  0: "Do Nothing",
  4: "RTL",
  9: "Camera Trigger",
  11: "Fence Enable",
  16: "AUTO Mode",
  22: "Parachute Release",
  24: "Auto Mission Reset",
  27: "Retract Mount1",
  28: "Relay1 On/Off",
  29: "Landing Gear",
  30: "Lost Plane Sound",
  31: "Motor Emergency Stop",
  34: "Relay2 On/Off",
  35: "Relay3 On/Off",
  36: "Relay4 On/Off",
  38: "ADSB Avoidance Enable",
  41: "ArmDisarm (4.1 and lower)",
  43: "InvertedFlight Enable",
  46: "RC Override Enable",
  51: "MANUAL Mode",
  52: "ACRO Mode",
  55: "GUIDED Mode",
  56: "LOITER Mode",
  58: "Clear Waypoints",
  62: "Compass Learn",
  64: "Reverse Throttle",
  65: "GPS Disable",
  66: "Relay5 On/Off",
  67: "Relay6 On/Off",
  72: "CIRCLE Mode",
  77: "TAKEOFF Mode",
  78: "RunCam Control",
  79: "RunCam OSD Control",
  81: "Disarm",
  82: "QAssist 3pos",
  84: "AirMode",
  85: "Generator",
  86: "Non Auto Terrain Follow Disable",
  87: "Crow Select",
  88: "Soaring Enable",
  89: "Landing Flare",
  90: "EKF Source Set",
  91: "Airspeed Ratio Calibration",
  92: "FBWA Mode",
  94: "VTX Power",
  95: "FBWA taildragger takeoff mode",
  96: "Trigger re-reading of mode switch",
  98: "TRAINING Mode",
  100: "KillIMU1",
  101: "KillIMU2",
  102: "Camera Mode Toggle",
  103: "EKF lane switch attempt",
  104: "EKF yaw reset",
  105: "GPS Disable Yaw",
  106: "Disable Airspeed Use",
  107: "Enable FW Autotune",
  108: "QRTL Mode",
  110: "KillIMU3",
  111: "Loweheiser starter",
  112: "SwitchExternalAHRS",
  113: "Retract Mount2",
  150: "CRUISE Mode",
  153: "ArmDisarm (4.2 and higher)",
  154: "ArmDisarm with Quadplane AirMode (4.2 and higher)",
  155: "Set roll pitch and yaw trim to current servo and RC",
  157: "Force FS Action to FBWA",
  158: "Optflow Calibration",
  160: "Weathervane Enable",
  162: "FFT Tune",
  163: "Mount Yaw Lock",
  164: "Pause Stream Logging",
  165: "Arm/Emergency Motor Stop",
  166: "Camera Record Video",
  167: "Camera Zoom",
  168: "Camera Manual Focus",
  169: "Camera Auto Focus",
  170: "QSTABILIZE Mode",
  171: "Calibrate Compasses",
  172: "Battery MPPT Enable",
  173: "Plane AUTO Mode Landing Abort",
  174: "Camera Image Tracking",
  175: "Camera Lens",
  176: "Quadplane Fwd Throttle Override enable",
  177: "Mount LRF enable",
  179: "ICEngine start / stop",
  180: "Test autotuned gains after tune is complete",
  181: "QuickTune",
  183: "AUTOLAND mode",
  184: "System ID Chirp",
  185: "Mount Roll/Pitch Lock",
  186: "Mount POI Lock",
  187: "EKF Reset",
  208: "Flap",
  209: "VTOL Forward Throttle",
  210: "Airbrakes",
  212: "Mount1 Roll",
  213: "Mount1 Pitch",
  214: "Mount1 Yaw",
  215: "Mount2 Roll",
  216: "Mount2 Pitch",
  217: "Mount2 Yaw",
  218: "Loweheiser throttle",
  300: "Scripting1",
  301: "Scripting2",
  302: "Scripting3",
  303: "Scripting4",
  304: "Scripting5",
  305: "Scripting6",
  306: "Scripting7",
  307: "Scripting8",
  308: "Scripting9",
  309: "Scripting10",
  310: "Scripting11",
  311: "Scripting12",
  312: "Scripting13",
  313: "Scripting14",
  314: "Scripting15",
  315: "Scripting16",
  316: "Stop-Restart Scripting",
};
